### ISSUE TITLE
Other products from array

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_template_office_jekyll#62]
An array with objects for each product: url, title, tag and all that is necessary to have good links. 

![Screen Shot 2020-11-18 at 10 14 55 AM](https://user-images.githubusercontent.com/411114/99513102-919ad080-298a-11eb-9d17-f08cc66aa8d7.png)

**Comment by edhenderson** [comment]
I am a little unsure what you want here, can you explain?

We have in `footer.html`:

```liquid
          {%- for item in footer.products -%}
          <li class="mb-3">
            <a href="{{item.link}}" class="text-reset">
              {{item.title}}
            </a>
          </li>
          {%- endfor -%}
```

which essentially is a loop of links of this data (in `footer.yml`)

```yml
products:
  - title: OpenVPN Server
    link : "#!"

  - title: Samba Server
    link : "#!"

  - title: Rsyslog Server
    link : "#!"
```
